### ISSUE TITLE
Great system - I might use it, if stable

### ISSUE THREAD

**Issue by MichaelVoelkel** [mfreiholz/Qt-Advanced-Docking-System#23]
I have already pulled and tried out this docking system and am very pleased with it so far. If this works stable, I would love to use it with my commercial Desktop app "PokerRanger". Your first release seems to be a beta, so I am not sure whether I can really utilize it as of now since I need a certain degree of stability. Do you happen to know of any large/possibly commercial applications that are interested in using it as well? Could be interesting to know

**Comment by mfreiholz** [comment]
The current master is very stable. I will create a new release-tag soon.

**Comment by mfreiholz** [comment]
I've created the first release and will keep compatibility within major version.
https://github.com/mfreiholz/Qt-Advanced-Docking-System/releases
