### ISSUE TITLE
Can this function be used in QML？

### ISSUE THREAD

**Issue by luoyayun361** [mfreiholz/Qt-Advanced-Docking-System#32]
This is a very good feature, but I want to use it in QML projects. Is there any support?

**Comment by MichaelVoelkel** [comment]
You closed this, but it does not really work with QML. What I personally do, though, is to have docks and use QML quick widgets within the particular docks, example: ![](https://www.pokerranger.com/assets/flexible-user-interface.png)
Quick widgets have many problems / things to think of, but it works stable enough.
